{
  "formatVersion": "1.1",
  "component": {
    "group": "org.modelingvalue.gradle",
    "module": "mvgplugin",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mvgplugin-2.3.3.jar",
          "url": "mvgplugin-2.3.3.jar",
          "size": 128001,
          "sha512": "16308efcc395eb4d865968ed133318d8beec1e36700d9943121e23a37a0efbf0ffb00900cfc2dddbcc1cabe631cac8de2b059094d0ef0096edc119f14aed5419",
          "sha256": "19c8439c984a613eac9f4e0fa76b3f25826da8e410aed56cfd5c101d20dadf49",
          "sha1": "a2c895f58b1a0aa1d97f33f0be0202ff6a81eefb",
          "md5": "7f5eb7591f6b30446774afb7b3723615"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.5.0.202512021534-r"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        }
      ],
      "files": [
        {
          "name": "mvgplugin-2.3.3.jar",
          "url": "mvgplugin-2.3.3.jar",
          "size": 128001,
          "sha512": "16308efcc395eb4d865968ed133318d8beec1e36700d9943121e23a37a0efbf0ffb00900cfc2dddbcc1cabe631cac8de2b059094d0ef0096edc119f14aed5419",
          "sha256": "19c8439c984a613eac9f4e0fa76b3f25826da8e410aed56cfd5c101d20dadf49",
          "sha1": "a2c895f58b1a0aa1d97f33f0be0202ff6a81eefb",
          "md5": "7f5eb7591f6b30446774afb7b3723615"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mvgplugin-2.3.3-javadoc.jar",
          "url": "mvgplugin-2.3.3-javadoc.jar",
          "size": 198909,
          "sha512": "2d32d6b8f00eb104a7e188a07e217f3b82fe895ecf39ba4052e9bcb6d8d2363835e25a5990043195e7005ac44470975fd0c6c17accf0d21350db52c8046f4961",
          "sha256": "c417f156873b0d3b9cf5ce7eff603a7f217fc93a5508696fd18c1d4393a36f2e",
          "sha1": "6bec75e22eb7fac23dbf5408ccfb9066146f873b",
          "md5": "e9d39aec784d2ba1e1dd189e6d2bcb62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mvgplugin-2.3.3-sources.jar",
          "url": "mvgplugin-2.3.3-sources.jar",
          "size": 71830,
          "sha512": "92210d2d9f1492bc50c3307de1c642374186914eaf47682c62088e039832422d398db9d54fc2b683af7e9f60ab874732e82c7e1e1afd867525bd778b6f4c403d",
          "sha256": "fc91c145155988eed6030ba4a1bfd1aa924c556d12be20ffd3326dab809b9b2e",
          "sha1": "8f70e1d7cebaaed19355c5f0dd2676daa0110e8b",
          "md5": "4c94e20b85aa4b4daee32ad327fa0411"
        }
      ]
    }
  ]
}
